package com.example.trading;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Signal represents a trading signal generated by the strategy.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Signal {
    private String symbol;
    private String side;
    private double price;
    private int quantity;
    private String timestamp;
}
